# Generated by Django 3.0.6 on 2020-06-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('a_1', models.CharField(max_length=256)),
                ('a_2', models.CharField(max_length=256)),
                ('a_3', models.CharField(max_length=256)),
                ('a_4', models.CharField(max_length=256)),
                ('correct', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('a_1', models.CharField(max_length=256)),
                ('a_2', models.CharField(max_length=256)),
                ('a_3', models.CharField(max_length=256)),
                ('a_4', models.CharField(max_length=256)),
                ('correct', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('a_1', models.CharField(max_length=256)),
                ('a_2', models.CharField(max_length=256)),
                ('a_3', models.CharField(max_length=256)),
                ('a_4', models.CharField(max_length=256)),
                ('correct', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('a_1', models.CharField(max_length=256)),
                ('a_2', models.CharField(max_length=256)),
                ('a_3', models.CharField(max_length=256)),
                ('a_4', models.CharField(max_length=256)),
                ('correct', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('a_1', models.CharField(max_length=256)),
                ('a_2', models.CharField(max_length=256)),
                ('a_3', models.CharField(max_length=256)),
                ('a_4', models.CharField(max_length=256)),
                ('correct', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('a_1', models.CharField(max_length=256)),
                ('a_2', models.CharField(max_length=256)),
                ('a_3', models.CharField(max_length=256)),
                ('a_4', models.CharField(max_length=256)),
                ('correct', models.CharField(max_length=8)),
            ],
        ),
    ]
