# Generated by Django 3.0.6 on 2020-06-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200602_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biology',
        ),
        migrations.DeleteModel(
            name='Entertainment',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Literature',
        ),
        migrations.DeleteModel(
            name='Science',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
