# Generated by Django 3.0.6 on 2020-06-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20200602_1713'),
        ('login', '0005_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='entertainment',
            field=models.ManyToManyField(to='category.Entertainment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='geography',
            field=models.ManyToManyField(to='category.Geography'),
        ),
    ]
