# Generated by Django 3.0.6 on 2020-06-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20200602_1739'),
        ('login', '0006_auto_20200602_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(to='category.History'),
        ),
        migrations.AddField(
            model_name='profile',
            name='literature',
            field=models.ManyToManyField(to='category.Literature'),
        ),
        migrations.AddField(
            model_name='profile',
            name='science',
            field=models.ManyToManyField(to='category.Science'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.ManyToManyField(to='category.Sport'),
        ),
    ]
