# Generated by Django 3.0.6 on 2020-06-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200602_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='entertainment',
        ),
        migrations.AddField(
            model_name='profile',
            name='entertainment',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='geography',
        ),
        migrations.AddField(
            model_name='profile',
            name='geography',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='history',
        ),
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='literature',
        ),
        migrations.AddField(
            model_name='profile',
            name='literature',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='science',
        ),
        migrations.AddField(
            model_name='profile',
            name='science',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sport',
        ),
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
