# Generated by Django 3.0.6 on 2020-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200602_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='entertainment',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='geography',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='history',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='literature',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='science',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sport',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
