# Generated by Django 3.0.6 on 2020-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20200602_1739'),
        ('login', '0010_auto_20200602_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='geography',
        ),
        migrations.AddField(
            model_name='profile',
            name='geography',
            field=models.ManyToManyField(default='', related_name='formats', to='category.Geography'),
        ),
    ]
