# Generated by Django 3.0.6 on 2020-06-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20200602_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='geography',
        ),
        migrations.AddField(
            model_name='profile',
            name='geography',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
