# Generated by Django 3.0.6 on 2020-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20200602_1739'),
        ('login', '0014_auto_20200602_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='geography',
        ),
        migrations.AddField(
            model_name='profile',
            name='geography',
            field=models.ManyToManyField(to='category.Geography'),
        ),
    ]
