# Generated by Django 3.0.6 on 2020-06-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20200602_1951'),
        ('login', '0015_auto_20200602_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='entertainment',
        ),
        migrations.AddField(
            model_name='profile',
            name='entertainment',
            field=models.ManyToManyField(to='category.Entertainment'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='history',
        ),
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(to='category.History'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='literature',
        ),
        migrations.AddField(
            model_name='profile',
            name='literature',
            field=models.ManyToManyField(to='category.Literature'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='science',
        ),
        migrations.AddField(
            model_name='profile',
            name='science',
            field=models.ManyToManyField(to='category.Science'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sport',
        ),
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.ManyToManyField(to='category.Sport'),
        ),
    ]
