# Generated by Django 3.0.6 on 2020-06-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biology',
            new_name='Geography',
        ),
    ]
