# Generated by Django 3.0.6 on 2020-06-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200602_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='user_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geography',
            name='user_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='user_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='literature',
            name='user_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='science',
            name='user_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='user_answered',
            field=models.BooleanField(default=False),
        ),
    ]
