# Generated by Django 3.0.6 on 2020-06-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20200602_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainment',
            name='user_answered',
        ),
        migrations.RemoveField(
            model_name='geography',
            name='user_answered',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user_answered',
        ),
        migrations.RemoveField(
            model_name='literature',
            name='user_answered',
        ),
        migrations.RemoveField(
            model_name='science',
            name='user_answered',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='user_answered',
        ),
    ]
