# Generated by Django 3.0.6 on 2020-06-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20200602_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='geography',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='literature',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='science',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sport',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
    ]
